[package]
name = "luminance-dummy"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
luminance = { path = "../luminance" }
luminance-glfw = { path = "../luminance-glfw" }
